/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>


#ifndef _Included_com_yjzn_Em3096Native
#define _Included_com_yjzn_Em3096Native
#ifdef __cplusplus
extern "C" {
#endif


JNIEXPORT void JNICALL Java_com_yjzn_Em3096Native_power(JNIEnv *, jobject,jint);




JNIEXPORT void JNICALL Java_com_yjzn_Em3096Native_start_1scan
  (JNIEnv *, jobject);
 
JNIEXPORT void JNICALL Java_com_yjzn_Em3096Native_stop_1scan
    (JNIEnv *, jobject);
#ifdef __cplusplus
}
#endif
#endif
