/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_camera_usbcamera_UVCJni */

#ifndef _Included_com_camera_usbcamera_UVCJni
#define _Included_com_camera_usbcamera_UVCJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_camera_usbcamera_UVCJni
 * Method:    prepareCamera
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_camera_usbcamera_UVCJni_prepareCamera
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_camera_usbcamera_UVCJni
 * Method:    getBufferSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_camera_usbcamera_UVCJni_getBufferSize
  (JNIEnv *, jclass);

/*
 * Class:     com_camera_usbcamera_UVCJni
 * Method:    setDirectBuffer
 * Signature: (Ljava/lang/Object;I)I
 */
JNIEXPORT jint JNICALL Java_com_camera_usbcamera_UVCJni_setDirectBuffer
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     com_camera_usbcamera_UVCJni
 * Method:    readFrame
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_camera_usbcamera_UVCJni_readFrame
  (JNIEnv *, jclass);

/*
 * Class:     com_camera_usbcamera_UVCJni
 * Method:    stopCamera
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_camera_usbcamera_UVCJni_stopCamera
  (JNIEnv *, jclass);

/*
 * Class:     com_camera_usbcamera_UVCJni
 * Method:    startRecording
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_camera_usbcamera_UVCJni_startRecording
  (JNIEnv *, jclass);

/*
 * Class:     com_camera_usbcamera_UVCJni
 * Method:    stopRecording
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_camera_usbcamera_UVCJni_stopRecording
  (JNIEnv *, jclass);

/*
 * Class:     com_camera_usbcamera_UVCJni
 * Method:    captureImage
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_camera_usbcamera_UVCJni_captureImage
  (JNIEnv *, jclass);

/*
 * Class:     com_camera_usbcamera_UVCJni
 * Method:    recording
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_camera_usbcamera_UVCJni_recording
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
